import "../styles/Base.scss"

export const GamesBase = () => {
  console.log("games")

  return (
    <div className="base">
      Games
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
      <p>TETS</p>
    </div>
  )
}
